version: "3.8"

services:
  redis:
    image: redislabs/rejson:2.0.6
    ports:
      - "6379:6379"
  compat:
    image: redislabs/rejson:2.0.6
    ports:
      - "6378:6379"
  sentinel:
    image: redislabs/rejson:2.0.6
    entrypoint:
      - /bin/bash
      - -c
      - |
        redis-server --save "" --appendonly no --port 6380 &
        echo "sentinel monitor test 127.0.0.1 6380 2\n" > sentinel.conf
        redis-server sentinel.conf --sentinel
    ports:
      - "6380:6380"
      - "26379:26379"
  cluster:
    image: redislabs/rejson:2.0.6
    entrypoint:
      - /bin/bash
      - -c
      - |
        redis-server --port 7001 --save "" --appendonly no --cluster-enabled yes --cluster-config-file 7001.conf &
        redis-server --port 7002 --save "" --appendonly no --cluster-enabled yes --cluster-config-file 7002.conf &
        redis-server --port 7003 --save "" --appendonly no --cluster-enabled yes --cluster-config-file 7003.conf &
        while ! redis-cli --cluster create 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 --cluster-yes; do sleep 1; done
        wait
    ports:
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"